version: "3.7"

services:
  waiter:
    container_name: waiter
    build: ../waiter
    environment: 
    - ENVIRONMENT=local
    network_mode: host
    volumes:
      - './resources/aws/:/root/.aws/'

  cook:
    container_name: cook
    build: ../cook
    environment: 
    - ENVIRONMENT=local
    network_mode: host
    volumes:
      - './resources/aws/:/root/.aws/'

  delivery:
    container_name: delivery
    build: ../delivery
    environment: 
    - ENVIRONMENT=local
    network_mode: host
    volumes:
      - './resources/aws/:/root/.aws/'

volumes:
  data-volume: