version: "3.7"

services:
  prometheus:
    image: prom/prometheus:v2.19.0
    container_name: prometheus
    volumes:
      - ./resources/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command: 
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    network_mode: host
    restart: always
  
  grafana:
    image: grafana/grafana:8.3.4
    container_name: grafana
    user: "472"
    depends_on:
      - prometheus
    network_mode: host
    volumes:
      - grafana_data:/var/lib/grafana
      - ./resources/grafana/provisioning:/etc/grafana/provisioning/
    env_file:
      - ./resources/grafana/config.monitoring
    restart: always  


volumes:
  prometheus_data: {}
  grafana_data: {}