package mocks

import (
	"placeholder/domain"

	"github.com/stretchr/testify/mock"
)

// AuthorRepository is an autogenerated mock type for the AuthorRepository type
type PoemUsecase struct {
	mock.Mock
}

func (_mock *PoemUsecase) Store(poem *domain.Poem) error {
	_mock.Called(poem)

	return nil
}

func (_mock *PoemUsecase) FetchUsecase() []domain.Poem {
	ret := _mock.Called()

	return ret.Get(0).([]domain.Poem)
}

func (_mock *PoemUsecase) FetchRandomUsecase() domain.Poem {
	ret := _mock.Called()

	return ret.Get(0).(domain.Poem)
}

func (_mock *PoemUsecase) FetchStaticUsecase() domain.Poem {
	ret := _mock.Called()

	return ret.Get(0).(domain.Poem)
}
